---
- name: Gather IP address of localhost
  hosts: localhost
  tasks:
    - shell: "ifconfig eth0"
      register: ip_addr
    - set_fact:
            ip_addr: "{{ ip_addr.stdout.split('\n')[1].split()[1] }}"
    - debug: var=ip_addr

        
